"""adjusted name for containerimages and runningapps

Revision ID: 0dfa267e7646
Revises: d58b90f0ec69
Create Date: 2024-04-21 14:50:15.753886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfa267e7646'
down_revision = 'd58b90f0ec69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_name')
    )
    op.create_table('running_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_image_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('date_launched', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_image_id'], ['container_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('running_apps')
    op.drop_table('container_images')
    # ### end Alembic commands ###
