"""Added HostStatus table

Revision ID: 234e28726a2e
Revises: fd2ea4b980d6
Create Date: 2024-05-01 21:15:12.363082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234e28726a2e'
down_revision = 'fd2ea4b980d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_status')
    # ### end Alembic commands ###
