"""Remove command field and add dport to ContainerImages

Revision ID: 49d0071bfe73
Revises: c6e1f1ca768c
Create Date: 2024-04-22 02:12:31.961749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d0071bfe73'
down_revision = 'c6e1f1ca768c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dport', sa.Integer(), nullable=True))
        batch_op.drop_column('command')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('dport')

    # ### end Alembic commands ###
