"""remove app_name

Revision ID: 705d9add0fac
Revises: 7e0ee7ec90f7
Create Date: 2024-04-22 02:58:16.289053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705d9add0fac'
down_revision = '7e0ee7ec90f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.drop_column('app_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
