"""adding app_name

Revision ID: 7e0ee7ec90f7
Revises: 49d0071bfe73
Create Date: 2024-04-22 02:55:51.831988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0ee7ec90f7'
down_revision = '49d0071bfe73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.drop_column('app_name')

    # ### end Alembic commands ###
