"""empty message

Revision ID: 812444c88b9e
Revises: d93fe59f0703
Create Date: 2024-04-30 00:58:28.084987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812444c88b9e'
down_revision = 'd93fe59f0703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_config')
    # ### end Alembic commands ###
