"""Add sudo_required column to Playbooks

Revision ID: 9d97d11e23e5
Revises: 9182aed5f225
Create Date: 2024-04-21 02:41:06.033028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d97d11e23e5'
down_revision = '9182aed5f225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sudo_required', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_column('sudo_required')

    # ### end Alembic commands ###
