"""empty message

Revision ID: 4ea1ab468b89
Revises: 
Create Date: 2024-08-04 21:19:44.265464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea1ab468b89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))

    # Populate the new author column with a default value
    # This uses a direct SQL command to update existing records
    op.execute("UPDATE playbooks SET author = 'unknown_author' WHERE author IS NULL")

    # Alter the column to be non-nullable
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.alter_column('author', existing_type=sa.String(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###