"""add port to running apps and command to container image

Revision ID: b49343435fa7
Revises: 0dfa267e7646
Create Date: 2024-04-21 22:35:55.638966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49343435fa7'
down_revision = '0dfa267e7646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command', sa.Text(), nullable=True))

    with op.batch_alter_table('running_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('running_apps', schema=None) as batch_op:
        batch_op.drop_column('port')

    with op.batch_alter_table('container_images', schema=None) as batch_op:
        batch_op.drop_column('command')

    # ### end Alembic commands ###
