"""adding containerimage and running app

Revision ID: d58b90f0ec69
Revises: 9d97d11e23e5
Create Date: 2024-04-21 14:46:29.157356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58b90f0ec69'
down_revision = '9d97d11e23e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_name')
    )
    op.create_table('running_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_image_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('date_launched', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_image_id'], ['container_image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('running_app')
    op.drop_table('container_image')
    # ### end Alembic commands ###
