"""empty message

Revision ID: dbebc4921f8e
Revises: 13b4f707a17d
Create Date: 2024-05-30 05:05:51.418881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbebc4921f8e'
down_revision = '13b4f707a17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('http_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('http_check', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
