version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: opsmanager_postgres
    environment:
      POSTGRES_DB: opsmanager       # Replace with your database name
      POSTGRES_USER: opsmanager         # Replace with your database user
      POSTGRES_PASSWORD: opsmanager # Replace with your database password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Map PostgreSQL port to host
    restart: unless-stopped
    networks:
      - opsmanager_network

  opsmanager:
    image: sandboxcsp/opsmanager:v1.2
    container_name: opsmanager_container
    env_file:
      - .env
    volumes:
      - ${HOME_DIR}/.ssh:/root/.ssh
      - vault_items:/app/vault_items
      - migrations:/app/migrations
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - opsmanager_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  vault_items:
    driver: local
  migrations:
    driver: local

networks:
  opsmanager_network:
    driver: bridge