---
- name: Install unzip on Debian servers
  hosts: all
  become: yes  # Use sudo to elevate privileges

  tasks:
    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present