name: Create production promotion pull request
on:
  push:
    branches:
      - integration
jobs:
  ProdPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin integration:integration
          git reset --hard integration
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: main